name: Go Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Go Tests
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.17' # or any other version: 1.x, 1.16, etc.

      - name: Check out code
        uses: actions/checkout@v2

      - name: Test with Go
        run: go test -v ./utils/...
