name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.x'
          
      - name: Install dependencies
        run: go mod vendor

      - name: Build
        run: go build -v -mod=vendor ./...

      - name: Test
        run: go test -v -mod=vendor ./...
